CREATE TABLE "asientos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "asientos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tanda_id" bigint NOT NULL,
	"identificador" varchar(20) NOT NULL,
	"fila" varchar(10),
	"numero" integer,
	"estado" text DEFAULT 'disponible' NOT NULL,
	CONSTRAINT "chk_asientos_numero_no_negativo" CHECK ("asientos"."numero" is null or "asientos"."numero" >= 0),
	CONSTRAINT "chk_asientos_estado" CHECK ("asientos"."estado" in ('disponible', 'reservado', 'vendido'))
);
--> statement-breakpoint
CREATE TABLE "eventos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eventos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organizador_id" bigint NOT NULL,
	"nombre" varchar(200) NOT NULL,
	"descripcion" text,
	"fecha_evento" timestamp with time zone NOT NULL,
	"lugar" varchar(200),
	"afiche_url" varchar(255),
	"aforo_total" integer,
	"es_gratuito" boolean DEFAULT false NOT NULL,
	"aprobacion_gratuito" text DEFAULT 'no_aplica' NOT NULL,
	"estado" text DEFAULT 'borrador' NOT NULL,
	"fecha_evento_original" timestamp with time zone,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chk_eventos_aforo_no_negativo" CHECK ("eventos"."aforo_total" is null or "eventos"."aforo_total" >= 0),
	CONSTRAINT "chk_eventos_aprobacion_gratuito" CHECK ("eventos"."aprobacion_gratuito" in ('no_aplica', 'pendiente', 'aprobado', 'rechazado')),
	CONSTRAINT "chk_eventos_estado" CHECK ("eventos"."estado" in ('borrador', 'publicado', 'reprogramado', 'finalizado', 'cancelado'))
);
--> statement-breakpoint
CREATE TABLE "faq_base_conocimiento" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "faq_base_conocimiento_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organizador_id" bigint,
	"pregunta" varchar(255) NOT NULL,
	"respuesta" text NOT NULL,
	"categoria" varchar(60)
);
--> statement-breakpoint
CREATE TABLE "liquidaciones" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "liquidaciones_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organizador_id" bigint NOT NULL,
	"periodo_inicio" date NOT NULL,
	"periodo_fin" date NOT NULL,
	"total_vendido" bigint DEFAULT 0 NOT NULL,
	"monto_comision_o_suscripcion" bigint DEFAULT 0 NOT NULL,
	"estado" text DEFAULT 'pendiente' NOT NULL,
	"liquidado_en" timestamp with time zone,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chk_liquidaciones_total_no_negativo" CHECK ("liquidaciones"."total_vendido" >= 0),
	CONSTRAINT "chk_liquidaciones_comision_no_negativa" CHECK ("liquidaciones"."monto_comision_o_suscripcion" >= 0),
	CONSTRAINT "chk_liquidaciones_estado" CHECK ("liquidaciones"."estado" in ('pendiente', 'liquidado'))
);
--> statement-breakpoint
CREATE TABLE "organizador_suscripciones" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organizador_suscripciones_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organizador_id" bigint NOT NULL,
	"plan_id" bigint,
	"estado" text DEFAULT 'activa' NOT NULL,
	"fecha_inicio" date NOT NULL,
	"fecha_proxima_facturacion" date,
	CONSTRAINT "chk_organizador_suscripciones_estado" CHECK ("organizador_suscripciones"."estado" in ('activa', 'mora', 'cancelada'))
);
--> statement-breakpoint
CREATE TABLE "pagos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pagos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ticket_id" bigint NOT NULL,
	"monto" bigint NOT NULL,
	"metodo" text DEFAULT 'transferencia' NOT NULL,
	"referencia_externa" varchar(120),
	"estado" text DEFAULT 'pendiente' NOT NULL,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chk_pagos_monto_no_negativo" CHECK ("pagos"."monto" >= 0),
	CONSTRAINT "chk_pagos_metodo" CHECK ("pagos"."metodo" in ('transferencia', 'tarjeta', 'billetera')),
	CONSTRAINT "chk_pagos_estado" CHECK ("pagos"."estado" in ('pendiente', 'pagado', 'rechazado'))
);
--> statement-breakpoint
CREATE TABLE "planes_suscripcion" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "planes_suscripcion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nombre" varchar(40) NOT NULL,
	"tickets_incluidos_mes" integer NOT NULL,
	"precio_mensual" bigint NOT NULL,
	"comision_excedente_pct" numeric(5, 2) DEFAULT '5.00' NOT NULL,
	"activo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "chk_planes_tickets_no_negativo" CHECK ("planes_suscripcion"."tickets_incluidos_mes" >= 0),
	CONSTRAINT "chk_planes_precio_no_negativo" CHECK ("planes_suscripcion"."precio_mensual" >= 0)
);
--> statement-breakpoint
CREATE TABLE "reembolsos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reembolsos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ticket_id" bigint NOT NULL,
	"evento_id" bigint NOT NULL,
	"canon_pagado" boolean DEFAULT false NOT NULL,
	"estado" text DEFAULT 'solicitado' NOT NULL,
	"solicitado_en" timestamp with time zone DEFAULT now() NOT NULL,
	"procesado_en" timestamp with time zone,
	CONSTRAINT "chk_reembolsos_estado" CHECK ("reembolsos"."estado" in ('solicitado', 'autorizado', 'procesado'))
);
--> statement-breakpoint
CREATE TABLE "staff_eventos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "staff_eventos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"staff_id" bigint NOT NULL,
	"evento_id" bigint NOT NULL,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "staff_invitaciones" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "staff_invitaciones_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token" varchar(64) NOT NULL,
	"organizador_id" bigint NOT NULL,
	"evento_id" bigint NOT NULL,
	"expira_en" timestamp with time zone NOT NULL,
	"usado_en" timestamp with time zone,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tandas" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tandas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"evento_id" bigint NOT NULL,
	"nombre" varchar(80) NOT NULL,
	"tipo" text DEFAULT 'general' NOT NULL,
	"precio" bigint DEFAULT 0 NOT NULL,
	"cantidad_total" integer DEFAULT 0 NOT NULL,
	"cantidad_vendida" integer DEFAULT 0 NOT NULL,
	"estado" text DEFAULT 'activa' NOT NULL,
	CONSTRAINT "chk_tandas_stock" CHECK ("tandas"."cantidad_vendida" <= "tandas"."cantidad_total"),
	CONSTRAINT "chk_tandas_precio_no_negativo" CHECK ("tandas"."precio" >= 0),
	CONSTRAINT "chk_tandas_cantidad_total_no_negativa" CHECK ("tandas"."cantidad_total" >= 0),
	CONSTRAINT "chk_tandas_cantidad_vendida_no_negativa" CHECK ("tandas"."cantidad_vendida" >= 0),
	CONSTRAINT "chk_tandas_tipo" CHECK ("tandas"."tipo" in ('general', 'numerada')),
	CONSTRAINT "chk_tandas_estado" CHECK ("tandas"."estado" in ('activa', 'agotada', 'inactiva'))
);
--> statement-breakpoint
CREATE TABLE "tickets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tickets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"codigo" varchar(40) NOT NULL,
	"evento_id" bigint NOT NULL,
	"tanda_id" bigint NOT NULL,
	"asiento_id" bigint,
	"comprador_id" bigint,
	"nombre_comprador" varchar(150) NOT NULL,
	"cedula" varchar(30),
	"email" varchar(150) NOT NULL,
	"contacto" varchar(30),
	"comprobante" varchar(100),
	"comprobante_archivo" varchar(255),
	"estado" text DEFAULT 'pendiente' NOT NULL,
	"es_cortesia" boolean DEFAULT false NOT NULL,
	"reservado_hasta" timestamp with time zone,
	"aprobado_por" bigint,
	"fecha_compra" timestamp with time zone DEFAULT now() NOT NULL,
	"hora_ingreso" timestamp with time zone,
	"actualizado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chk_tickets_estado" CHECK ("tickets"."estado" in ('pendiente', 'disponible', 'usado', 'anulado'))
);
--> statement-breakpoint
CREATE TABLE "usuarios" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usuarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nombre" varchar(150) NOT NULL,
	"email" varchar(150) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"rol" text NOT NULL,
	"telefono" varchar(30),
	"cedula" varchar(30),
	"estado" text DEFAULT 'activo' NOT NULL,
	"motivo_rechazo" varchar(255),
	"ruc_facturacion" varchar(30),
	"tyc_aceptado_en" timestamp with time zone,
	"invitado_por" bigint,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chk_usuarios_rol" CHECK ("usuarios"."rol" in ('superadmin', 'organizador', 'staff', 'comprador')),
	CONSTRAINT "chk_usuarios_estado" CHECK ("usuarios"."estado" in ('pendiente_aprobacion', 'rechazado', 'activo', 'inactivo', 'mora'))
);
--> statement-breakpoint
ALTER TABLE "asientos" ADD CONSTRAINT "fk_asientos_tanda" FOREIGN KEY ("tanda_id") REFERENCES "public"."tandas"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eventos" ADD CONSTRAINT "fk_eventos_organizador" FOREIGN KEY ("organizador_id") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "faq_base_conocimiento" ADD CONSTRAINT "fk_faq_organizador" FOREIGN KEY ("organizador_id") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "liquidaciones" ADD CONSTRAINT "fk_liquidaciones_organizador" FOREIGN KEY ("organizador_id") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organizador_suscripciones" ADD CONSTRAINT "fk_organizador_suscripciones_organizador" FOREIGN KEY ("organizador_id") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organizador_suscripciones" ADD CONSTRAINT "fk_organizador_suscripciones_plan" FOREIGN KEY ("plan_id") REFERENCES "public"."planes_suscripcion"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pagos" ADD CONSTRAINT "fk_pagos_ticket" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reembolsos" ADD CONSTRAINT "fk_reembolsos_ticket" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reembolsos" ADD CONSTRAINT "fk_reembolsos_evento" FOREIGN KEY ("evento_id") REFERENCES "public"."eventos"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "staff_eventos" ADD CONSTRAINT "fk_staff_eventos_staff" FOREIGN KEY ("staff_id") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "staff_eventos" ADD CONSTRAINT "fk_staff_eventos_evento" FOREIGN KEY ("evento_id") REFERENCES "public"."eventos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "staff_invitaciones" ADD CONSTRAINT "fk_staff_invitaciones_organizador" FOREIGN KEY ("organizador_id") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "staff_invitaciones" ADD CONSTRAINT "fk_staff_invitaciones_evento" FOREIGN KEY ("evento_id") REFERENCES "public"."eventos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tandas" ADD CONSTRAINT "fk_tandas_evento" FOREIGN KEY ("evento_id") REFERENCES "public"."eventos"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_evento" FOREIGN KEY ("evento_id") REFERENCES "public"."eventos"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_tanda" FOREIGN KEY ("tanda_id") REFERENCES "public"."tandas"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_asiento" FOREIGN KEY ("asiento_id") REFERENCES "public"."asientos"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_comprador" FOREIGN KEY ("comprador_id") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_aprobado_por" FOREIGN KEY ("aprobado_por") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usuarios" ADD CONSTRAINT "fk_usuarios_invitado_por" FOREIGN KEY ("invitado_por") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_asientos_tanda_identificador" ON "asientos" USING btree ("tanda_id","identificador");--> statement-breakpoint
CREATE INDEX "idx_asientos_libres" ON "asientos" USING btree ("tanda_id","id") WHERE "asientos"."estado" = 'disponible';--> statement-breakpoint
CREATE INDEX "idx_eventos_organizador" ON "eventos" USING btree ("organizador_id");--> statement-breakpoint
CREATE INDEX "idx_eventos_publicos" ON "eventos" USING btree ("fecha_evento") WHERE "eventos"."estado" = 'publicado';--> statement-breakpoint
CREATE INDEX "idx_liquidaciones_organizador" ON "liquidaciones" USING btree ("organizador_id");--> statement-breakpoint
CREATE INDEX "idx_organizador_suscripciones_organizador" ON "organizador_suscripciones" USING btree ("organizador_id");--> statement-breakpoint
CREATE INDEX "idx_pagos_ticket" ON "pagos" USING btree ("ticket_id");--> statement-breakpoint
CREATE INDEX "idx_reembolsos_evento" ON "reembolsos" USING btree ("evento_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_staff_eventos" ON "staff_eventos" USING btree ("staff_id","evento_id");--> statement-breakpoint
CREATE INDEX "idx_staff_eventos_evento" ON "staff_eventos" USING btree ("evento_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_staff_invitaciones_token" ON "staff_invitaciones" USING btree ("token");--> statement-breakpoint
CREATE INDEX "idx_tandas_evento" ON "tandas" USING btree ("evento_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_tickets_codigo" ON "tickets" USING btree ("codigo");--> statement-breakpoint
CREATE INDEX "idx_tickets_evento" ON "tickets" USING btree ("evento_id");--> statement-breakpoint
CREATE INDEX "idx_tickets_estado" ON "tickets" USING btree ("estado");--> statement-breakpoint
CREATE INDEX "idx_tickets_reservado_hasta" ON "tickets" USING btree ("reservado_hasta");--> statement-breakpoint
CREATE INDEX "idx_tickets_evento_estado" ON "tickets" USING btree ("evento_id","estado");--> statement-breakpoint
CREATE INDEX "idx_tickets_tanda" ON "tickets" USING btree ("tanda_id");--> statement-breakpoint
CREATE INDEX "idx_tickets_comprador" ON "tickets" USING btree ("comprador_id","fecha_compra");--> statement-breakpoint
CREATE INDEX "idx_tickets_pendientes" ON "tickets" USING btree ("fecha_compra") WHERE "tickets"."estado" = 'pendiente';--> statement-breakpoint
CREATE INDEX "idx_tickets_reserva" ON "tickets" USING btree ("reservado_hasta") WHERE "tickets"."estado" = 'pendiente';--> statement-breakpoint
CREATE UNIQUE INDEX "uq_usuarios_email_lower" ON "usuarios" USING btree (lower("email"));