-- ============================================================================
-- Fase 5 del plan de mejoras (Cambios_web.txt) — tabla `ordenes`: la unidad
-- de aprobación/pago. Hoy sigue siendo 1:1 con un ticket (una compra = un
-- ticket = una orden), pero es el prerrequisito estructural del carrito
-- (Fase 6): cuando exista, un carrito de N entradas pagadas con un solo
-- comprobante se aprueba/rechaza como UNA orden, no como N tickets sueltos.
--
-- De paso arregla un bug latente: aprobarTicket dejaba el asiento en
-- 'reservado' para siempre en vez de pasarlo a 'vendido' al aprobar una
-- compra numerada paga. Ver el nuevo aprobarOrden en src/server/tickets.ts.
-- ============================================================================

CREATE TABLE ordenes (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	codigo varchar(40) NOT NULL,
	organizador_id bigint NOT NULL,
	comprador_id bigint,
	nombre_comprador varchar(150) NOT NULL,
	cedula varchar(30),
	email varchar(150) NOT NULL,
	contacto varchar(30),
	comprobante varchar(100),
	comprobante_archivo varchar(255),
	subtotal bigint NOT NULL DEFAULT 0,
	descuento bigint NOT NULL DEFAULT 0,
	total bigint GENERATED ALWAYS AS (subtotal - descuento) STORED NOT NULL,
	cantidad_tickets integer NOT NULL DEFAULT 1,
	estado text NOT NULL DEFAULT 'pendiente',
	reservado_hasta timestamptz,
	aprobado_por bigint,
	creado_en timestamptz NOT NULL DEFAULT now(),
	actualizado_en timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE UNIQUE INDEX uq_ordenes_codigo ON ordenes (codigo);
--> statement-breakpoint
CREATE INDEX idx_ordenes_organizador_estado ON ordenes (organizador_id, estado);
--> statement-breakpoint
CREATE INDEX idx_ordenes_comprador ON ordenes (comprador_id, creado_en);
--> statement-breakpoint
CREATE INDEX idx_ordenes_pendientes ON ordenes (creado_en) WHERE estado = 'pendiente';
--> statement-breakpoint
CREATE INDEX idx_ordenes_reserva ON ordenes (reservado_hasta) WHERE estado = 'pendiente';
--> statement-breakpoint

ALTER TABLE ordenes ADD CONSTRAINT fk_ordenes_organizador FOREIGN KEY (organizador_id) REFERENCES usuarios(id) ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE ordenes ADD CONSTRAINT fk_ordenes_comprador FOREIGN KEY (comprador_id) REFERENCES usuarios(id) ON DELETE SET NULL;
--> statement-breakpoint
ALTER TABLE ordenes ADD CONSTRAINT fk_ordenes_aprobado_por FOREIGN KEY (aprobado_por) REFERENCES usuarios(id) ON DELETE SET NULL;
--> statement-breakpoint

ALTER TABLE ordenes ADD CONSTRAINT chk_ordenes_subtotal_no_negativo CHECK (subtotal >= 0);
--> statement-breakpoint
ALTER TABLE ordenes ADD CONSTRAINT chk_ordenes_descuento_no_negativo CHECK (descuento >= 0);
--> statement-breakpoint
ALTER TABLE ordenes ADD CONSTRAINT chk_ordenes_descuento_max CHECK (descuento <= subtotal);
--> statement-breakpoint
ALTER TABLE ordenes ADD CONSTRAINT chk_ordenes_cantidad_tickets_positiva CHECK (cantidad_tickets >= 1);
--> statement-breakpoint
ALTER TABLE ordenes ADD CONSTRAINT chk_ordenes_estado CHECK (estado in ('pendiente', 'pagada', 'rechazada', 'vencida'));
--> statement-breakpoint

-- Mismo trigger que ya mantiene tickets.actualizado_en (fijar_actualizado_en,
-- ver drizzle/0001_triggers_y_deferrable.sql) — reutilizado, no redefinido.
CREATE TRIGGER trg_ordenes_actualizado_en
BEFORE UPDATE ON ordenes
FOR EACH ROW
EXECUTE FUNCTION fijar_actualizado_en();
--> statement-breakpoint

-- ----------------------------------------------------------------------------
-- tickets.orden_id: nullable primero, backfill, RECIÉN AHÍ NOT NULL — mismo
-- patrón que precio_unitario en la Fase 4 (0002).
-- ----------------------------------------------------------------------------
ALTER TABLE tickets ADD COLUMN orden_id bigint;
--> statement-breakpoint

-- Backfill: una orden 1:1 por cada ticket ya existente. Código sintético
-- 'ORD-LEGACY-<id del ticket>' — fácil de reconocer como backfill en soporte,
-- y sirve de llave para el UPDATE de abajo sin necesitar una tabla puente.
-- comprobante_archivo se deja NULL a propósito: el archivo de estos tickets
-- viejos se queda donde está (tickets.comprobante_archivo) — la lectura hace
-- COALESCE(orden.comprobante_archivo, ticket.comprobante_archivo).
INSERT INTO ordenes (
	codigo, organizador_id, comprador_id, nombre_comprador, cedula, email, contacto,
	comprobante, subtotal, descuento, cantidad_tickets, estado, reservado_hasta,
	aprobado_por, creado_en
)
SELECT
	'ORD-LEGACY-' || tk.id,
	e.organizador_id,
	tk.comprador_id,
	tk.nombre_comprador,
	tk.cedula,
	tk.email,
	tk.contacto,
	tk.comprobante,
	tk.precio_unitario,
	tk.descuento,
	1,
	CASE tk.estado
		WHEN 'pendiente' THEN 'pendiente'
		WHEN 'anulado'   THEN 'rechazada'
		ELSE 'pagada' -- 'disponible' y 'usado'
	END,
	tk.reservado_hasta,
	tk.aprobado_por,
	tk.fecha_compra
  FROM tickets tk
  JOIN eventos e ON e.id = tk.evento_id;
--> statement-breakpoint

UPDATE tickets tk
   SET orden_id = o.id
  FROM ordenes o
 WHERE o.codigo = 'ORD-LEGACY-' || tk.id;
--> statement-breakpoint

ALTER TABLE tickets ALTER COLUMN orden_id SET NOT NULL;
--> statement-breakpoint
CREATE INDEX idx_tickets_orden ON tickets (orden_id);
--> statement-breakpoint
ALTER TABLE tickets ADD CONSTRAINT fk_tickets_orden FOREIGN KEY (orden_id) REFERENCES ordenes(id) ON DELETE RESTRICT;
