-- ============================================================================
-- Fase 7 del plan de mejoras (Cambios_web.txt) — cupones de descuento del
-- organizador. Se apoya en las Fases 4 (precio congelado en el ticket) y 5
-- (ordenes): ambas ya dan lugar para guardar un descuento sin tocar nada
-- más. Todavía sin carrito (Fase 6): una compra sigue siendo 1 ticket, así
-- que el descuento de un cupón nunca necesita repartirse entre varios
-- tickets — eso queda para cuando el carrito exista.
-- ============================================================================

CREATE TABLE cupones (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizador_id bigint NOT NULL,
	evento_id bigint,
	codigo varchar(40) NOT NULL,
	tipo text NOT NULL,
	valor bigint NOT NULL,
	max_usos integer,
	usos integer NOT NULL DEFAULT 0,
	max_usos_por_comprador integer DEFAULT 1,
	monto_minimo bigint NOT NULL DEFAULT 0,
	vence_en timestamptz,
	activo boolean NOT NULL DEFAULT true,
	creado_en timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- Código único GLOBAL (no por organizador): el comprador lo tipea sin haber
-- elegido organizador — dos cupones con el mismo código serían ambiguos.
CREATE UNIQUE INDEX uq_cupones_codigo ON cupones (lower(codigo));
--> statement-breakpoint
CREATE INDEX idx_cupones_organizador ON cupones (organizador_id);
--> statement-breakpoint

ALTER TABLE cupones ADD CONSTRAINT fk_cupones_organizador FOREIGN KEY (organizador_id) REFERENCES usuarios(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE cupones ADD CONSTRAINT fk_cupones_evento FOREIGN KEY (evento_id) REFERENCES eventos(id) ON DELETE CASCADE;
--> statement-breakpoint

ALTER TABLE cupones ADD CONSTRAINT chk_cupones_tipo CHECK (tipo in ('porcentaje', 'monto'));
--> statement-breakpoint
ALTER TABLE cupones ADD CONSTRAINT chk_cupones_valor_porcentaje CHECK (tipo <> 'porcentaje' or (valor between 1 and 100));
--> statement-breakpoint
ALTER TABLE cupones ADD CONSTRAINT chk_cupones_valor_monto CHECK (tipo <> 'monto' or valor > 0);
--> statement-breakpoint
ALTER TABLE cupones ADD CONSTRAINT chk_cupones_usos_no_negativo CHECK (usos >= 0);
--> statement-breakpoint
-- El guardián de verdad: el tope no se puede exceder ni con un bug de la app.
ALTER TABLE cupones ADD CONSTRAINT chk_cupones_usos_max CHECK (max_usos is null or usos <= max_usos);
--> statement-breakpoint
ALTER TABLE cupones ADD CONSTRAINT chk_cupones_monto_minimo_no_negativo CHECK (monto_minimo >= 0);
--> statement-breakpoint

-- ----------------------------------------------------------------------------
-- ordenes.cupon_id / codigo_cupon — nullable desde el día uno (ninguna orden
-- vieja usó cupón, así que no hace falta backfill acá, a diferencia de
-- precio_unitario en la Fase 4).
-- ----------------------------------------------------------------------------
ALTER TABLE ordenes ADD COLUMN cupon_id bigint;
--> statement-breakpoint
ALTER TABLE ordenes ADD COLUMN codigo_cupon varchar(40);
--> statement-breakpoint
ALTER TABLE ordenes ADD CONSTRAINT fk_ordenes_cupon FOREIGN KEY (cupon_id) REFERENCES cupones(id) ON DELETE SET NULL;
--> statement-breakpoint

-- ----------------------------------------------------------------------------
-- cupon_usos — auditoría de uso. uq_cupon_usos_orden es lo que impide que
-- una misma orden consuma dos veces un cupón.
-- ----------------------------------------------------------------------------
CREATE TABLE cupon_usos (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cupon_id bigint NOT NULL,
	orden_id bigint NOT NULL,
	comprador_id bigint,
	email varchar(150) NOT NULL,
	monto_descontado bigint NOT NULL,
	creado_en timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE UNIQUE INDEX uq_cupon_usos_orden ON cupon_usos (cupon_id, orden_id);
--> statement-breakpoint
CREATE INDEX idx_cupon_usos_email ON cupon_usos (cupon_id, lower(email));
--> statement-breakpoint

ALTER TABLE cupon_usos ADD CONSTRAINT fk_cupon_usos_cupon FOREIGN KEY (cupon_id) REFERENCES cupones(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE cupon_usos ADD CONSTRAINT fk_cupon_usos_orden FOREIGN KEY (orden_id) REFERENCES ordenes(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE cupon_usos ADD CONSTRAINT fk_cupon_usos_comprador FOREIGN KEY (comprador_id) REFERENCES usuarios(id) ON DELETE SET NULL;
--> statement-breakpoint
ALTER TABLE cupon_usos ADD CONSTRAINT chk_cupon_usos_monto_no_negativo CHECK (monto_descontado >= 0);
