-- ============================================================================
-- Fase 8 del plan de mejoras (Cambios_web.txt) — código de vendedor/
-- referido + premios por compartir. Tampoco depende del carrito (Fase 6,
-- todavía sin construir): la atribución se congela directo en `ordenes` al
-- comprar, en vez de en un carrito previo.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- usuarios.codigo_referido — nullable desde el día uno (nadie tenía código
-- todavía), generado perezosamente al entrar a /panel/cuenta.
-- ----------------------------------------------------------------------------
ALTER TABLE usuarios ADD COLUMN codigo_referido varchar(12);
--> statement-breakpoint
CREATE UNIQUE INDEX uq_usuarios_codigo_referido ON usuarios (lower(codigo_referido));
--> statement-breakpoint

-- ----------------------------------------------------------------------------
-- programas_referidos
-- ----------------------------------------------------------------------------
CREATE TABLE programas_referidos (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizador_id bigint NOT NULL,
	evento_id bigint,
	nombre varchar(80) NOT NULL,
	ventas_requeridas integer NOT NULL,
	tipo_premio text NOT NULL DEFAULT 'cortesia',
	tanda_premio_id bigint,
	max_premios_por_usuario integer,
	monto_minimo_venta bigint NOT NULL DEFAULT 1,
	inicia_en timestamptz,
	termina_en timestamptz,
	activo boolean NOT NULL DEFAULT true,
	creado_en timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE INDEX idx_programas_referidos_organizador ON programas_referidos (organizador_id, activo);
--> statement-breakpoint

ALTER TABLE programas_referidos ADD CONSTRAINT fk_programas_referidos_organizador FOREIGN KEY (organizador_id) REFERENCES usuarios(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE programas_referidos ADD CONSTRAINT fk_programas_referidos_evento FOREIGN KEY (evento_id) REFERENCES eventos(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE programas_referidos ADD CONSTRAINT fk_programas_referidos_tanda_premio FOREIGN KEY (tanda_premio_id) REFERENCES tandas(id) ON DELETE RESTRICT;
--> statement-breakpoint

ALTER TABLE programas_referidos ADD CONSTRAINT chk_programas_referidos_tipo_premio CHECK (tipo_premio in ('cortesia'));
--> statement-breakpoint
ALTER TABLE programas_referidos ADD CONSTRAINT chk_programas_referidos_ventas_requeridas CHECK (ventas_requeridas >= 1);
--> statement-breakpoint
ALTER TABLE programas_referidos ADD CONSTRAINT chk_programas_referidos_tanda_premio_si_cortesia CHECK (tipo_premio <> 'cortesia' or tanda_premio_id is not null);
--> statement-breakpoint
ALTER TABLE programas_referidos ADD CONSTRAINT chk_programas_referidos_monto_minimo CHECK (monto_minimo_venta >= 0);
--> statement-breakpoint

-- ----------------------------------------------------------------------------
-- ordenes.referido_por_usuario_id / codigo_referido — nullable, sin
-- backfill (ninguna orden vieja tuvo referido).
-- ----------------------------------------------------------------------------
ALTER TABLE ordenes ADD COLUMN referido_por_usuario_id bigint;
--> statement-breakpoint
ALTER TABLE ordenes ADD COLUMN codigo_referido varchar(12);
--> statement-breakpoint
ALTER TABLE ordenes ADD CONSTRAINT fk_ordenes_referido_por FOREIGN KEY (referido_por_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL;
--> statement-breakpoint

-- ----------------------------------------------------------------------------
-- referidos_ventas — uq_referidos_ventas_orden: una orden se atribuye una
-- sola vez, estructuralmente.
-- ----------------------------------------------------------------------------
CREATE TABLE referidos_ventas (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	referidor_id bigint NOT NULL,
	orden_id bigint NOT NULL,
	organizador_id bigint NOT NULL,
	evento_id bigint NOT NULL,
	cantidad_tickets integer NOT NULL,
	monto bigint NOT NULL,
	estado text NOT NULL DEFAULT 'pendiente',
	confirmada_en timestamptz,
	creado_en timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE UNIQUE INDEX uq_referidos_ventas_orden ON referidos_ventas (orden_id);
--> statement-breakpoint
CREATE INDEX idx_referidos_ventas_conteo ON referidos_ventas (referidor_id, organizador_id, estado);
--> statement-breakpoint

ALTER TABLE referidos_ventas ADD CONSTRAINT fk_referidos_ventas_referidor FOREIGN KEY (referidor_id) REFERENCES usuarios(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE referidos_ventas ADD CONSTRAINT fk_referidos_ventas_orden FOREIGN KEY (orden_id) REFERENCES ordenes(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE referidos_ventas ADD CONSTRAINT fk_referidos_ventas_organizador FOREIGN KEY (organizador_id) REFERENCES usuarios(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE referidos_ventas ADD CONSTRAINT fk_referidos_ventas_evento FOREIGN KEY (evento_id) REFERENCES eventos(id) ON DELETE CASCADE;
--> statement-breakpoint

ALTER TABLE referidos_ventas ADD CONSTRAINT chk_referidos_ventas_cantidad CHECK (cantidad_tickets >= 1);
--> statement-breakpoint
ALTER TABLE referidos_ventas ADD CONSTRAINT chk_referidos_ventas_monto_no_negativo CHECK (monto >= 0);
--> statement-breakpoint
ALTER TABLE referidos_ventas ADD CONSTRAINT chk_referidos_ventas_estado CHECK (estado in ('pendiente', 'valida', 'anulada'));
--> statement-breakpoint

-- ----------------------------------------------------------------------------
-- premios_referidos — uq_premios_referidos_umbral es lo que hace el
-- otorgamiento seguro sin locks (ver comentario en esquema.ts).
-- ----------------------------------------------------------------------------
CREATE TABLE premios_referidos (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	programa_id bigint NOT NULL,
	referidor_id bigint NOT NULL,
	ventas_consumidas integer NOT NULL,
	estado text NOT NULL DEFAULT 'otorgado',
	ticket_cortesia_id bigint,
	otorgado_en timestamptz NOT NULL DEFAULT now(),
	entregado_en timestamptz
);
--> statement-breakpoint

CREATE UNIQUE INDEX uq_premios_referidos_umbral ON premios_referidos (programa_id, referidor_id, ventas_consumidas);
--> statement-breakpoint
CREATE INDEX idx_premios_referidos_referidor ON premios_referidos (referidor_id);
--> statement-breakpoint

ALTER TABLE premios_referidos ADD CONSTRAINT fk_premios_referidos_programa FOREIGN KEY (programa_id) REFERENCES programas_referidos(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE premios_referidos ADD CONSTRAINT fk_premios_referidos_referidor FOREIGN KEY (referidor_id) REFERENCES usuarios(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE premios_referidos ADD CONSTRAINT fk_premios_referidos_ticket_cortesia FOREIGN KEY (ticket_cortesia_id) REFERENCES tickets(id) ON DELETE SET NULL;
--> statement-breakpoint

ALTER TABLE premios_referidos ADD CONSTRAINT chk_premios_referidos_ventas_consumidas CHECK (ventas_consumidas >= 1);
--> statement-breakpoint
ALTER TABLE premios_referidos ADD CONSTRAINT chk_premios_referidos_estado CHECK (estado in ('otorgado', 'pendiente_stock', 'entregado', 'anulado'));
