-- ============================================================================
-- Fase 6 del plan de mejoras (Cambios_web.txt) — carrito con reserva real.
-- tandas.cantidad_reservada + las tablas carritos/carrito_items. La reserva
-- nunca se escribe con +=/-=: se recalcula entera desde carrito_items en
-- cada mutación (ver server/carrito.ts::recalcularReservada) — así una
-- reserva no puede driftear en silencio, y un carrito vencido deja de
-- contar en el instante en que vence, sin esperar a ningún barrido.
-- ============================================================================

ALTER TABLE tandas ADD COLUMN cantidad_reservada integer NOT NULL DEFAULT 0;
--> statement-breakpoint
ALTER TABLE tandas ADD CONSTRAINT chk_tandas_cantidad_reservada_no_negativa CHECK (cantidad_reservada >= 0);
--> statement-breakpoint

-- Postgres no tiene ALTER CONSTRAINT para un CHECK — se recrea entero.
-- Mismo nombre a propósito: errores-pg.ts ya lo mapea a un mensaje amigable.
ALTER TABLE tandas DROP CONSTRAINT chk_tandas_stock;
--> statement-breakpoint
ALTER TABLE tandas ADD CONSTRAINT chk_tandas_stock CHECK (cantidad_vendida + cantidad_reservada <= cantidad_total);
--> statement-breakpoint

CREATE TABLE carritos (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	token varchar(64) NOT NULL,
	organizador_id bigint,
	estado text NOT NULL DEFAULT 'activo',
	expira_en timestamptz,
	creado_en timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE UNIQUE INDEX uq_carritos_token ON carritos (token);
--> statement-breakpoint
CREATE INDEX idx_carritos_activos ON carritos (expira_en) WHERE estado = 'activo';
--> statement-breakpoint

ALTER TABLE carritos ADD CONSTRAINT fk_carritos_organizador FOREIGN KEY (organizador_id) REFERENCES usuarios(id) ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE carritos ADD CONSTRAINT chk_carritos_estado CHECK (estado in ('activo', 'completado', 'vencido'));
--> statement-breakpoint

CREATE TABLE carrito_items (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	carrito_id bigint NOT NULL,
	tanda_id bigint NOT NULL,
	cantidad integer NOT NULL DEFAULT 1,
	agregado_en timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE UNIQUE INDEX uq_carrito_items_carrito_tanda ON carrito_items (carrito_id, tanda_id);
--> statement-breakpoint
CREATE INDEX idx_carrito_items_tanda ON carrito_items (tanda_id);
--> statement-breakpoint

ALTER TABLE carrito_items ADD CONSTRAINT fk_carrito_items_carrito FOREIGN KEY (carrito_id) REFERENCES carritos(id) ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE carrito_items ADD CONSTRAINT fk_carrito_items_tanda FOREIGN KEY (tanda_id) REFERENCES tandas(id) ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE carrito_items ADD CONSTRAINT chk_carrito_items_cantidad CHECK (cantidad >= 1 AND cantidad <= 20);
