import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  type ExtraConfigColumn,
  foreignKey,
  index,
  integer,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";
import {
  APROBACION_GRATUITO,
  ESTADOS_ASIENTO,
  ESTADOS_EVENTO,
  ESTADOS_LIQUIDACION,
  ESTADOS_PAGO,
  ESTADOS_REEMBOLSO,
  ESTADOS_SUSCRIPCION,
  ESTADOS_TANDA,
  ESTADOS_TICKET,
  ESTADOS_USUARIO,
  METODOS_PAGO,
  ROLES,
  TIPOS_TANDA,
} from "@/lib/constantes";

/**
 * Esquema PostgreSQL — traducción de sql/schema.sql (MariaDB) del proyecto PHP.
 * Ver plan de migración §4 para las decisiones de traducción. Resumen:
 *  - BIGINT UNSIGNED AUTO_INCREMENT → bigint GENERATED BY DEFAULT AS IDENTITY
 *    ("by default", no "always": permite insertar IDs explícitos en la
 *    migración de datos sin OVERRIDING SYSTEM VALUE).
 *  - ENUM(...) → text + CHECK (no CREATE TYPE nativo — ver §4.2: la migración
 *    de datos es más simple y agregar/quitar valores no reescribe la tabla).
 *    Los dominios viven en una sola fuente de verdad: src/lib/constantes.ts.
 *  - DECIMAL(12,0)/DECIMAL(14,0) (montos en guaraníes, sin decimales) →
 *    bigint + CHECK >= 0 (no numeric: llegaría como string por el driver).
 *  - DATETIME → timestamp with time zone (timestamptz). La zona horaria de
 *    aplicación es America/Asuncion (ver §4.4) — la migración de datos
 *    convierte explícitamente, nunca implícitamente.
 *  - Los 2 triggers de borrado (trg_tandas_delete_bd, trg_eventos_delete_bd)
 *    y el nuevo trigger de tickets.actualizado_en no son representables acá
 *    (Drizzle no genera plpgsql) — viven en una migración SQL a mano
 *    (drizzle/0001_triggers.sql, generada con `drizzle-kit generate --custom`).
 *  - Los FK se dejan DEFERRABLE INITIALLY IMMEDIATE en esa misma migración a
 *    mano, para que el script de migración de datos pueda cargar las 13
 *    tablas dentro de una única transacción con constraints diferidos.
 */

function checkEnum(
  nombre: string,
  columna: ExtraConfigColumn,
  valores: readonly string[],
) {
  const lista = valores.map((v) => `'${v}'`).join(", ");
  return check(nombre, sql`${columna} in (${sql.raw(lista)})`);
}

// ---------------------------------------------------------------------------
// usuarios — los 4 roles en una sola tabla
// ---------------------------------------------------------------------------
export const usuarios = pgTable(
  "usuarios",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    nombre: varchar("nombre", { length: 150 }).notNull(),
    email: varchar("email", { length: 150 }).notNull(),
    passwordHash: varchar("password_hash", { length: 255 }).notNull(),
    rol: text("rol").notNull(),
    telefono: varchar("telefono", { length: 30 }),
    cedula: varchar("cedula", { length: 30 }),
    estado: text("estado").notNull().default("activo"),
    motivoRechazo: varchar("motivo_rechazo", { length: 255 }),
    rucFacturacion: varchar("ruc_facturacion", { length: 30 }),
    tycAceptadoEn: timestamp("tyc_aceptado_en", { withTimezone: true }),
    invitadoPor: bigint("invitado_por", { mode: "number" }),
    creadoEn: timestamp("creado_en", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // MariaDB compara emails sin distinguir mayúsculas (collation *_ci);
    // Postgres es case-sensitive por defecto. Este índice + el login por
    // lower(email) replican esa semántica (ver plan §7.5, validación #10).
    uniqueIndex("uq_usuarios_email_lower").on(sql`lower(${t.email})`),
    foreignKey({
      name: "fk_usuarios_invitado_por",
      columns: [t.invitadoPor],
      foreignColumns: [t.id],
    }).onDelete("set null"),
    checkEnum("chk_usuarios_rol", t.rol, ROLES),
    checkEnum("chk_usuarios_estado", t.estado, ESTADOS_USUARIO),
  ],
);

// ---------------------------------------------------------------------------
// eventos
// ---------------------------------------------------------------------------
export const eventos = pgTable(
  "eventos",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    organizadorId: bigint("organizador_id", { mode: "number" }).notNull(),
    nombre: varchar("nombre", { length: 200 }).notNull(),
    descripcion: text("descripcion"),
    fechaEvento: timestamp("fecha_evento", { withTimezone: true }).notNull(),
    lugar: varchar("lugar", { length: 200 }),
    aficheUrl: varchar("afiche_url", { length: 255 }),
    aforoTotal: integer("aforo_total"),
    esGratuito: boolean("es_gratuito").notNull().default(false),
    aprobacionGratuito: text("aprobacion_gratuito").notNull().default("no_aplica"),
    estado: text("estado").notNull().default("borrador"),
    fechaEventoOriginal: timestamp("fecha_evento_original", { withTimezone: true }),
    creadoEn: timestamp("creado_en", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("idx_eventos_organizador").on(t.organizadorId),
    // Listado público + sitemap + home: solo se busca por fecha entre los publicados.
    index("idx_eventos_publicos")
      .on(t.fechaEvento)
      .where(sql`${t.estado} = 'publicado'`),
    foreignKey({
      name: "fk_eventos_organizador",
      columns: [t.organizadorId],
      foreignColumns: [usuarios.id],
    }).onDelete("restrict"),
    check("chk_eventos_aforo_no_negativo", sql`${t.aforoTotal} is null or ${t.aforoTotal} >= 0`),
    checkEnum("chk_eventos_aprobacion_gratuito", t.aprobacionGratuito, APROBACION_GRATUITO),
    checkEnum("chk_eventos_estado", t.estado, ESTADOS_EVENTO),
  ],
);

// ---------------------------------------------------------------------------
// tandas (tipos de entrada)
// ---------------------------------------------------------------------------
export const tandas = pgTable(
  "tandas",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    eventoId: bigint("evento_id", { mode: "number" }).notNull(),
    nombre: varchar("nombre", { length: 80 }).notNull(),
    tipo: text("tipo").notNull().default("general"),
    // DECIMAL(12,0) en guaraníes (sin decimales) → bigint, no numeric (ver §4.1:
    // numeric llegaría como string del driver y rompería las sumas del dashboard).
    precio: bigint("precio", { mode: "number" }).notNull().default(0),
    cantidadTotal: integer("cantidad_total").notNull().default(0),
    cantidadVendida: integer("cantidad_vendida").notNull().default(0),
    estado: text("estado").notNull().default("activa"),
  },
  (t) => [
    index("idx_tandas_evento").on(t.eventoId),
    foreignKey({
      name: "fk_tandas_evento",
      columns: [t.eventoId],
      foreignColumns: [eventos.id],
    }).onDelete("restrict"),
    check("chk_tandas_stock", sql`${t.cantidadVendida} <= ${t.cantidadTotal}`),
    check("chk_tandas_precio_no_negativo", sql`${t.precio} >= 0`),
    check("chk_tandas_cantidad_total_no_negativa", sql`${t.cantidadTotal} >= 0`),
    check("chk_tandas_cantidad_vendida_no_negativa", sql`${t.cantidadVendida} >= 0`),
    checkEnum("chk_tandas_tipo", t.tipo, TIPOS_TANDA),
    checkEnum("chk_tandas_estado", t.estado, ESTADOS_TANDA),
  ],
);

// ---------------------------------------------------------------------------
// asientos (solo para tandas numeradas)
// ---------------------------------------------------------------------------
export const asientos = pgTable(
  "asientos",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    tandaId: bigint("tanda_id", { mode: "number" }).notNull(),
    identificador: varchar("identificador", { length: 20 }).notNull(),
    fila: varchar("fila", { length: 10 }),
    numero: integer("numero"),
    estado: text("estado").notNull().default("disponible"),
  },
  (t) => [
    uniqueIndex("uq_asientos_tanda_identificador").on(t.tandaId, t.identificador),
    // El SELECT ... FOR UPDATE SKIP LOCKED de la compra numerada solo busca
    // asientos disponibles: índice parcial, se achica solo con las ventas.
    index("idx_asientos_libres")
      .on(t.tandaId, t.id)
      .where(sql`${t.estado} = 'disponible'`),
    foreignKey({
      name: "fk_asientos_tanda",
      columns: [t.tandaId],
      foreignColumns: [tandas.id],
    }).onDelete("restrict"),
    check("chk_asientos_numero_no_negativo", sql`${t.numero} is null or ${t.numero} >= 0`),
    checkEnum("chk_asientos_estado", t.estado, ESTADOS_ASIENTO),
  ],
);

// ---------------------------------------------------------------------------
// tickets
// ---------------------------------------------------------------------------
export const tickets = pgTable(
  "tickets",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    codigo: varchar("codigo", { length: 40 }).notNull(),
    eventoId: bigint("evento_id", { mode: "number" }).notNull(),
    tandaId: bigint("tanda_id", { mode: "number" }).notNull(),
    asientoId: bigint("asiento_id", { mode: "number" }),
    compradorId: bigint("comprador_id", { mode: "number" }),
    nombreComprador: varchar("nombre_comprador", { length: 150 }).notNull(),
    cedula: varchar("cedula", { length: 30 }),
    email: varchar("email", { length: 150 }).notNull(),
    contacto: varchar("contacto", { length: 30 }),
    comprobante: varchar("comprobante", { length: 100 }),
    // Solo el basename (ej. "EIK-XXXX.jpg"), nunca la ruta — ver plan §3(d).
    comprobanteArchivo: varchar("comprobante_archivo", { length: 255 }),
    estado: text("estado").notNull().default("pendiente"),
    esCortesia: boolean("es_cortesia").notNull().default(false),
    reservadoHasta: timestamp("reservado_hasta", { withTimezone: true }),
    aprobadoPor: bigint("aprobado_por", { mode: "number" }),
    fechaCompra: timestamp("fecha_compra", { withTimezone: true }).notNull().defaultNow(),
    horaIngreso: timestamp("hora_ingreso", { withTimezone: true }),
    // Se actualiza sola por trigger (drizzle/..._triggers.sql), nunca a mano:
    // el dashboard agrupa cancelaciones por DATE(actualizado_en).
    actualizadoEn: timestamp("actualizado_en", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_tickets_codigo").on(t.codigo),
    index("idx_tickets_evento").on(t.eventoId),
    index("idx_tickets_estado").on(t.estado),
    index("idx_tickets_reservado_hasta").on(t.reservadoHasta),
    index("idx_tickets_evento_estado").on(t.eventoId, t.estado),
    index("idx_tickets_tanda").on(t.tandaId),
    index("idx_tickets_comprador").on(t.compradorId, t.fechaCompra),
    // Cola de aprobación (superadmin y organizador).
    index("idx_tickets_pendientes")
      .on(t.fechaCompra)
      .where(sql`${t.estado} = 'pendiente'`),
    // Barrido de reservas vencidas.
    index("idx_tickets_reserva")
      .on(t.reservadoHasta)
      .where(sql`${t.estado} = 'pendiente'`),
    foreignKey({
      name: "fk_tickets_evento",
      columns: [t.eventoId],
      foreignColumns: [eventos.id],
    }).onDelete("restrict"),
    foreignKey({
      name: "fk_tickets_tanda",
      columns: [t.tandaId],
      foreignColumns: [tandas.id],
    }).onDelete("restrict"),
    foreignKey({
      name: "fk_tickets_asiento",
      columns: [t.asientoId],
      foreignColumns: [asientos.id],
    }).onDelete("restrict"),
    foreignKey({
      name: "fk_tickets_comprador",
      columns: [t.compradorId],
      foreignColumns: [usuarios.id],
    }).onDelete("set null"),
    foreignKey({
      name: "fk_tickets_aprobado_por",
      columns: [t.aprobadoPor],
      foreignColumns: [usuarios.id],
    }).onDelete("set null"),
    checkEnum("chk_tickets_estado", t.estado, ESTADOS_TICKET),
  ],
);

// ---------------------------------------------------------------------------
// pagos (verificación de transferencias — sin endpoints hoy, se migra igual)
// ---------------------------------------------------------------------------
export const pagos = pgTable(
  "pagos",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    ticketId: bigint("ticket_id", { mode: "number" }).notNull(),
    monto: bigint("monto", { mode: "number" }).notNull(),
    metodo: text("metodo").notNull().default("transferencia"),
    referenciaExterna: varchar("referencia_externa", { length: 120 }),
    estado: text("estado").notNull().default("pendiente"),
    creadoEn: timestamp("creado_en", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("idx_pagos_ticket").on(t.ticketId),
    foreignKey({
      name: "fk_pagos_ticket",
      columns: [t.ticketId],
      foreignColumns: [tickets.id],
    }).onDelete("restrict"),
    check("chk_pagos_monto_no_negativo", sql`${t.monto} >= 0`),
    checkEnum("chk_pagos_metodo", t.metodo, METODOS_PAGO),
    checkEnum("chk_pagos_estado", t.estado, ESTADOS_PAGO),
  ],
);

// ---------------------------------------------------------------------------
// staff_eventos (pivote staff ↔ evento)
// ---------------------------------------------------------------------------
export const staffEventos = pgTable(
  "staff_eventos",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    staffId: bigint("staff_id", { mode: "number" }).notNull(),
    eventoId: bigint("evento_id", { mode: "number" }).notNull(),
    creadoEn: timestamp("creado_en", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_staff_eventos").on(t.staffId, t.eventoId),
    index("idx_staff_eventos_evento").on(t.eventoId),
    foreignKey({
      name: "fk_staff_eventos_staff",
      columns: [t.staffId],
      foreignColumns: [usuarios.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_staff_eventos_evento",
      columns: [t.eventoId],
      foreignColumns: [eventos.id],
    }).onDelete("cascade"),
  ],
);

// ---------------------------------------------------------------------------
// staff_invitaciones (link de un solo uso)
// ---------------------------------------------------------------------------
export const staffInvitaciones = pgTable(
  "staff_invitaciones",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    token: varchar("token", { length: 64 }).notNull(),
    organizadorId: bigint("organizador_id", { mode: "number" }).notNull(),
    eventoId: bigint("evento_id", { mode: "number" }).notNull(),
    expiraEn: timestamp("expira_en", { withTimezone: true }).notNull(),
    usadoEn: timestamp("usado_en", { withTimezone: true }),
    creadoEn: timestamp("creado_en", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_staff_invitaciones_token").on(t.token),
    foreignKey({
      name: "fk_staff_invitaciones_organizador",
      columns: [t.organizadorId],
      foreignColumns: [usuarios.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_staff_invitaciones_evento",
      columns: [t.eventoId],
      foreignColumns: [eventos.id],
    }).onDelete("cascade"),
  ],
);

// ---------------------------------------------------------------------------
// planes_suscripcion
// ---------------------------------------------------------------------------
export const planesSuscripcion = pgTable(
  "planes_suscripcion",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    nombre: varchar("nombre", { length: 40 }).notNull(),
    ticketsIncluidosMes: integer("tickets_incluidos_mes").notNull(),
    precioMensual: bigint("precio_mensual", { mode: "number" }).notNull(),
    comisionExcedentePct: numeric("comision_excedente_pct", { precision: 5, scale: 2 })
      .notNull()
      .default("5.00"),
    activo: boolean("activo").notNull().default(true),
  },
  (t) => [
    check("chk_planes_tickets_no_negativo", sql`${t.ticketsIncluidosMes} >= 0`),
    check("chk_planes_precio_no_negativo", sql`${t.precioMensual} >= 0`),
  ],
);

// ---------------------------------------------------------------------------
// organizador_suscripciones (sin endpoints hoy, se migra igual)
// ---------------------------------------------------------------------------
export const organizadorSuscripciones = pgTable(
  "organizador_suscripciones",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    organizadorId: bigint("organizador_id", { mode: "number" }).notNull(),
    planId: bigint("plan_id", { mode: "number" }),
    estado: text("estado").notNull().default("activa"),
    fechaInicio: date("fecha_inicio").notNull(),
    fechaProximaFacturacion: date("fecha_proxima_facturacion"),
  },
  (t) => [
    index("idx_organizador_suscripciones_organizador").on(t.organizadorId),
    foreignKey({
      name: "fk_organizador_suscripciones_organizador",
      columns: [t.organizadorId],
      foreignColumns: [usuarios.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_organizador_suscripciones_plan",
      columns: [t.planId],
      foreignColumns: [planesSuscripcion.id],
    }).onDelete("set null"),
    checkEnum("chk_organizador_suscripciones_estado", t.estado, ESTADOS_SUSCRIPCION),
  ],
);

// ---------------------------------------------------------------------------
// liquidaciones
// ---------------------------------------------------------------------------
export const liquidaciones = pgTable(
  "liquidaciones",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    organizadorId: bigint("organizador_id", { mode: "number" }).notNull(),
    periodoInicio: date("periodo_inicio").notNull(),
    periodoFin: date("periodo_fin").notNull(),
    totalVendido: bigint("total_vendido", { mode: "number" }).notNull().default(0),
    montoComisionOSuscripcion: bigint("monto_comision_o_suscripcion", { mode: "number" })
      .notNull()
      .default(0),
    estado: text("estado").notNull().default("pendiente"),
    liquidadoEn: timestamp("liquidado_en", { withTimezone: true }),
    creadoEn: timestamp("creado_en", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("idx_liquidaciones_organizador").on(t.organizadorId),
    foreignKey({
      name: "fk_liquidaciones_organizador",
      columns: [t.organizadorId],
      foreignColumns: [usuarios.id],
    }).onDelete("cascade"),
    check("chk_liquidaciones_total_no_negativo", sql`${t.totalVendido} >= 0`),
    check(
      "chk_liquidaciones_comision_no_negativa",
      sql`${t.montoComisionOSuscripcion} >= 0`,
    ),
    checkEnum("chk_liquidaciones_estado", t.estado, ESTADOS_LIQUIDACION),
  ],
);

// ---------------------------------------------------------------------------
// reembolsos (sin endpoints hoy, se migra igual)
// ---------------------------------------------------------------------------
export const reembolsos = pgTable(
  "reembolsos",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    ticketId: bigint("ticket_id", { mode: "number" }).notNull(),
    eventoId: bigint("evento_id", { mode: "number" }).notNull(),
    canonPagado: boolean("canon_pagado").notNull().default(false),
    estado: text("estado").notNull().default("solicitado"),
    solicitadoEn: timestamp("solicitado_en", { withTimezone: true }).notNull().defaultNow(),
    procesadoEn: timestamp("procesado_en", { withTimezone: true }),
  },
  (t) => [
    index("idx_reembolsos_evento").on(t.eventoId),
    foreignKey({
      name: "fk_reembolsos_ticket",
      columns: [t.ticketId],
      foreignColumns: [tickets.id],
    }).onDelete("restrict"),
    foreignKey({
      name: "fk_reembolsos_evento",
      columns: [t.eventoId],
      foreignColumns: [eventos.id],
    }).onDelete("restrict"),
    checkEnum("chk_reembolsos_estado", t.estado, ESTADOS_REEMBOLSO),
  ],
);

// ---------------------------------------------------------------------------
// faq_base_conocimiento (RAG del chatbot futuro — sin endpoints hoy)
// ---------------------------------------------------------------------------
export const faqBaseConocimiento = pgTable(
  "faq_base_conocimiento",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    organizadorId: bigint("organizador_id", { mode: "number" }),
    pregunta: varchar("pregunta", { length: 255 }).notNull(),
    respuesta: text("respuesta").notNull(),
    categoria: varchar("categoria", { length: 60 }),
  },
  (t) => [
    foreignKey({
      name: "fk_faq_organizador",
      columns: [t.organizadorId],
      foreignColumns: [usuarios.id],
    }).onDelete("cascade"),
  ],
);
